const jobslist = [
{
'title': 'Senior iOS Developer',
'companyname': 'GenX Studio',
'location': 'Delhi, India',
'type': 'Full time',
'Duration': '2 days',
'applications': '24 applicants',
'logo': 'assets/Icons/Ic_Bookmark.png',
'avatar': 'assets/Icons/Ic_Bookmark.png',
},
  {
    'title': 'iOS Developer',
    'companyname': 'Emdad AI Khebrat Co.',
    'location': 'Riyadh, Saudi Arabia',
    'type': 'Part time',
    'Duration': '2 days',
    'applications': '24 applicants',
    'logo': 'assets/Icons/Ic_Bookmark.png',
    'avatar': '',
  },
  {
    'title': 'UI/UX Desinger',
    'companyname': 'Khebrat Co.',
    'location': 'Nodia, India',
    'type': 'Remote',
    'Duration': '2 days',
    'applications': '24 applicants',
    'logo': 'assets/Icons/Ic_Bookmark.png',
    'avatar': '',
  },
  {
    'title': 'Android Developer',
    'companyname': 'Emdad AI Khebrat Co.',
    'location': 'Kolkatta, India',
    'type': 'Remote',
    'Duration': '2 days',
    'applications': '24 applicants',
    'logo': 'assets/Icons/Ic_Bookmark.png',
    'avatar': '',
  },
  {
    'title': 'Graphics Desinger',
    'companyname': 'Nykaa',
    'location': 'Mumbai, India',
    'type': 'Full time',
    'Duration': '2 days',
    'applications': '24 applicants',
    'logo': 'assets/Icons/Ic_Bookmark.png',
    'avatar': '',
  },
  {
    'title': 'Graphics Desinger',
    'companyname': 'Nykaa',
    'location': 'Mumbai, India',
    'type': 'Full time',
    'Duration': '2 days',
    'applications': '24 applicants',
    'logo': 'assets/Icons/Ic_Bookmark.png',
    'avatar': '',
  },
];